wandb_version: 1

L:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1683269189.407609
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      - 42
      4: 3.10.9
      5: 0.14.0
      8:
      - 5
batch_size:
  desc: null
  value: 262144
encoding:
  desc: null
  value: positionally encoded
iters:
  desc: null
  value: 100000
learning_rate:
  desc: null
  value: 0.0001
